paths: 
  raw_data: data/${dataset.subset}/raw
  test_data: data/${dataset.subset}/test
  noise_data: data/${dataset.subset}/noise
  # source_separated_data: data/${dataset.subset}/source_separated
  # birdnetlib_analyzed_data: data/${dataset.subset}/birdnetlib_analyzed
  segmented_data: data/${dataset.subset}/segmented
  # balanced_data: data/${dataset.subset}/balanced
  polyphonic_data: data/${dataset.subset}/polyphonic

  #raw_data_info: data/${dataset.subset}/stage_results/raw_data_info
  raw_data_metadata: data/${dataset.subset}/stage_results/raw_data_metadata.json
  source_separation_metadata: data/${dataset.subset}/stage_results/source_separation_metadata.json
  analysis_metadata: data/${dataset.subset}/stage_results/analysis_metadata.json

random:
  random_seed: 42

dataset:
  subset: HSN

source_separation:
  model_dir: resources/bird_mixit_model_checkpoints/output_sources4
  checkpoint: resources/bird_mixit_model_checkpoints/output_sources4/model.ckpt-3223090
  sampling_rate: 22050 # bird mixit needs 22050 Hz
  max_duration_s: 30
  cpu_percentage: 0.8
  gb_per_worker: 1

analysis:
  sampling_rate: 48000 # birdnetlib needs 48kHz, internal resampling does not work with RecordingBuffer

segmentation:
  segment_length_in_s: 5
#   min_confidence: 0.9
# min_detection_percentage: 0.9

balance_dataset:
  method: undersample
  max_per_file: None

mix:
  max_polyphony_degree: 6
  signal_levels: [-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]
  snr_values: [-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  mix_levels: [-12, -11, -10, -9, -8, -7, -6]

upload:
  huggingface_user: mcht67